name: fmgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - scikit-learn
  - matplotlib
  - opencv
  - pip:
      - third_party/diff-gaussian-rasterization
      - third_party/simple-knn
      - third_party/simple-diff-gaussian-rasterization
      - jaxtyping
      - open_clip_torch
      - timm
      - ftfy
      - regex
      - clip @ git+https://github.com/openai/CLIP.git
      - git+https://github.com/facebookresearch/segment-anything.git
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
